return {
    -- "nvim-tree/nvim-tree.lua",
    -- event = "VeryLazy",
    -- config = function()
    --     local api = require("nvim-tree.api")
    --
    --     local function my_on_attach(bufnr)
    --         local function opts(desc)
    --             return { desc = "nvim-tree: " .. desc, buffer = bufnr, noremap = true, silent = true, nowait = true }
    --         end
    --
    --         -- Apply default mappings
    --         api.config.mappings.default_on_attach(bufnr)
    --
    --         -- Ensure API methods are defined before using them
    --         local function safely_set_keymap(mode, lhs, rhs, desc)
    --             if rhs then
    --                 vim.keymap.set(mode, lhs, rhs, opts(desc))
    --             end
    --         end
    --
    --         -- Custom mappings
    --         safely_set_keymap('n', 'l', api.node.open.edit, 'Open')
    --         safely_set_keymap('n', 'h', api.node.close, 'Close Node')
    --         safely_set_keymap('n', '<space>', function() end, 'No Action') -- Placeholder for no action
    --     end
    --
    --     require("nvim-tree").setup({
    --         sort = {
    --             sorter = "case_sensitive",
    --         },
    --         view = {
    --             width = 30,
    --             signcolumn = "no",
    --         },
    --         renderer = {
    --             group_empty = true,
    --             indent_markers = {
    --                 enable = true,
    --             },
    --         },
    --         filters = {
    --             dotfiles = true,
    --         },
    --         on_attach = my_on_attach,
    --     })
    -- end,
    -- keys = {
    --     -- Keymap for root directory
    --     { "<leader>eE", "<cmd>NvimTreeToggle<cr>", desc = "Explorer NvimTree (Root Dir)" },
    --     -- Keymap for current directory (by default NvimTree shows the current directory)
    --     { "<leader>ec", "<cmd>NvimTreeFindFile<cr>", desc = "Explorer NvimTree (cwd)" },
    --     -- Keymap for config directory
    --     { "<leader>eC", "<cmd>edit ~/.config/nvim<cr>", desc = "Explorer NvimTree (Config Dir)" },
    -- },
}


